export enum ActionTypes {
    LOGIN_SUCCESS = "LOGIN_SUCCESS",
    LOGIN_FAILURE = "LOGIN_FAILURE",
    LOGOUT = "LOGOUT",
    ADD_ZONE = "ADD_ZONE",
    REMOVE_ZONE = "REMOVE_ZONE",
    UPDATE_ZONE = "UPDATE_ZONE",
    GET_ZONES = "GET_ZONES"
}